#!/usr/bin/env bash

# Function to display information about a specific subdomain
display_info() {
    subdomain="$1"
    domain="$2"
    record_type=$(dig +short -t A "$subdomain.$domain" | awk '{print length ? "A" : "CNAME"}')
    destination=$(dig +short "$subdomain.$domain")
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main function
main() {
    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]; then
        # Display information for default subdomains
        display_info "www" "$domain"
        display_info "lb-01" "$domain"
        display_info "web-01" "$domain"
        display_info "web-02" "$domain"
    else
        # Display information for the specified subdomain
        display_info "$subdomain" "$domain"
    fi
}

# Check for mandatory arguments
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

main "$@"

