#!/usr/bin/env bash
#Indefinitely writes I am alive! to the file /tmp/my_process and
#pause for 2 seconds
#When passing the argument start:
#  Starts manage_my_process
#  Creates a file containing its PID in /var/run/my_process.pid
#  Displays manage_my_process started
#When passing the argument stop:
#  Stops manage_my_process
#  Deletes the file /var/run/my_process.pid
#  Displays manage_my_process stopped
#When passing the argument restart
#  Stops manage_my_process
#  Deletes the file /var/run/my_process.pid
#  Starts manage_my_process
#  Creates a file containing its PID in /var/run/my_process.pid
#  Displays manage_my_process restarted
#Displays Usage: manage_my_process {start|stop|restart}
#if any other argument or no argument is passed

if [ "${1}" == "start" ]
then
	./manage_my_process &
	sudo touch /var/run/my_process.pid
	sudo bash -c 'echo $$ > /var/run/myscript.pid'
	echo "manage_my_process started"
elif [	"${1}" == "stop" ]
then
	echo "manage_my_process stopped"
	sudo kill "$(cat /var/run/my_process.pid)"
	sudo rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
	sudo kill "$(cat /var/run/my_process.pid)"
	sudo rm /var/run/my_process.pid
	./manage_my_process &
	sudo touch /var/run/my_process.pid
	sudo bash -c 'echo $$ > /var/run/myscript.pid'
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
