#!/usr/bin/env bash
#Bash script that displays the visitor IP along
#with the HTTP status code from the Apache log file.
#Format: IP HTTP_CODE 

logfile="apache-access.log"

if [ ! -f $logfile ];
then
	echo "Apache logfile: $logfile not found."
	exit 1
fi

awk '{print $1, $9}' "$logfile" | column -c columns
