#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#    localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts ~/hosts.backup
echo "127.0.0.2		localhost" > ~/hosts.backup
echo "8.8.8.8		facebook.com" >> ~/hosts.backup
sudo cp -f ~/hosts.backup /etc/hosts
